### ISSUE TITLE
Improvements on conformance page

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa-dev.github.io#148]
Our current conformance page is very simple in functionality, so it would be great to add a bit more improvements on the UX side to make it a bit more usable overall. 

### List of possible improvements

- [ ] Search bar for tests/suites/both.
- [x] Instantly show the test name when hovering on the outcome square. (#152)
- [ ] Add a checkbox to hide all passed tests.
- [x] Enable using the Go back and Go forward buttons to return to the last visited tag/suite/test. (#150)
- [ ] Show the tests as a list of test names.
- [x] Hide empty suites when the ES version selector changes. (#153)
- [x] Sort tests alphabetically. (#151)

**Comment by nekevss** [comment]
I'd really like the test results to be alphabetically sorted (not hard, just haven't gotten around to it).

Another idea I think it'd be interesting to explore is an "Open in Playground" option that will load the test into the Boa playground, which would be really cool combined with boa-dev/boa#3227

**Comment by jedel1043** [comment]
> I'd really like the test results to be alphabetically sorted (not hard, just haven't gotten around to it).

Why stop there? We could also allow sorting by ES version, by outcome result, inverse alphabetical, etc.

**Comment by nekevss** [comment]
We can definitely expand on that. Mostly wanted it as the default :laughing:
